### ISSUE TITLE
035-policies checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/hpc-best-practices-webinars#18]
**Preparing to advertise webinar**
- [x] obtain preliminary webinar information
- [x] create presenter record(s)
- [x] create webinar record
- [x] verify

**Advertising webinar**
- [x] add full event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
- [x] add upcoming event to <https://ideas-productivity.org/events/>
- [x] add upcoming event to <https://ideas-productivity.org/>
- [x] add BSSw Event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
- [x] prepare and send MailChimp campaign

**Preparing for event**
- [ ] add event metadata
*Send connection email*

**Post-event artifact collection**
- [ ] obtain webinar registration list
- [ ] obtain webinar participation list
- [ ] obtain slides
- [ ] obtain Q&A
- [ ] obtain recording(s)

**Artifact archiving**
- [ ] upload recording(s) to YouTube
- [ ] upload slides to i-p.o
- [ ] upload Q&A to i-p.o
- [ ] add archive information to webinar record

**Webinar followup communications**
- [ ] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/hpcbp-webinars-cc.md>
- [ ] add webinar registrants to MailChimp audience
- [ ] add webinar participants to MailChimp audience
- [ ] prepare and send MailChimp campaign
