### ISSUE TITLE
test 035-policies checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/hpc-best-practices-webinars#20]
**Preparing to advertise webinar**
- [x] obtain preliminary webinar information
  - [x] webinar date
  - [x] webinar title
  - [x] webinar registration-url
  - [x] webinar ecp-abbreviation
  - [x] webinar abstract
  - [x] presenter name(s)
  - [x] presenter email(s)
  - [x] presenter affiliation(s)
  - [x] presenter github id(s)
  - [x] presenter bio(s)
- [x] technical editor checks webinar abstract
- [x] create presenter record(s)
- [x] create webinar record
- [x] verify content and formatting

**Advertising webinar**
- [x] add full upcoming event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
- [x] add upcoming event bullet to <https://ideas-productivity.org/events/>
- [x] add upcoming event bullet to <https://ideas-productivity.org/>
- [x] add BSSw Event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
- [x] prepare and send MailChimp campaign to full audience

**Preparing for event**
- [ ] add event metadata
  - [ ] vtc-url
  - [ ] vtc-session
  - [ ] vtc-password
  - [ ] qa-public-url
  - [ ] survey public-url
*Send connection email*

**Post-event artifact collection**
- [ ] obtain webinar registration list
- [ ] obtain webinar participation list
- [ ] obtain slides
- [ ] obtain Q&A
- [ ] obtain recording(s)

**Artifact archiving**
- [ ] upload recording(s) to YouTube
- [ ] upload slides to i-p.o
- [ ] upload Q&A to i-p.o
- [ ] add archive information to webinar record
  - [ ] archives

**Webinar followup communications**
- [ ] remove full upcoming event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
- [ ] add full past event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
- [ ] remove upcoming event bullet to <https://ideas-productivity.org/events/>
- [ ] add past event bullet to <https://ideas-productivity.org/events/>
- [ ] remove upcoming event bullet to <https://ideas-productivity.org/>
- [ ] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/hpcbp-webinars-cc.md>
- [ ] add webinar registrants to MailChimp audience w/ appropriate tag
- [ ] add webinar participants to MailChimp audience w/ appropriate tag
- [ ] prepare and send MailChimp campaign to appropriate tag
