### ISSUE TITLE
Test anything checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/hpc-best-practices-webinars#21]
**Preparing to advertise webinar**
- [ ] collect initial webinar information
  - [ ] webinar `date`
  - [ ] webinar `title`
  - [ ] webinar abstract
  - [ ] presenter name(s)
  - [ ] presenter email(s)
  - [ ] presenter affiliation(s)
  - [ ] presenter github id(s)
  - [ ] presenter bio(s)
- [ ] technical editor checks webinar abstract
- [ ] create presenter record(s)
- [ ] create webinar record
- [ ] verify content and formatting
- [ ] *update EventBrite*
  - [ ] *add full upcoming event*
  - [ ] obtain `registration-url`
  - [ ] add `registration-url` to webinar record
- [ ] verify content and formatting

**Advertising webinar**
- [ ] *update ECP training site*
  - [ ] *add full upcoming event*
  - [ ] obtain `ecp-abbreviation`
  - [ ] add `ecp-abbreviation` to webinar record
- [ ] verify content and formatting
- [ ] update i-p.o site
  - [ ] add full upcoming event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [ ] add upcoming event bullet to <https://ideas-productivity.org/events/>
  - [ ] add upcoming event bullet to <https://ideas-productivity.org/>
- [ ] add BSSw Event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
- [ ] prepare and send MailChimp campaign to full audience

**Preparing for event**
- [ ] add event metadata
  - [ ] vtc-url
  - [ ] vtc-session
  - [ ] vtc-password
  - [ ] qa-public-url
  - [ ] survey public-url
- [ ] *send connection email*

**Post-event artifact collection**
- [ ] obtain webinar registration list
- [ ] obtain webinar participation list
- [ ] obtain slides
- [ ] obtain Q&A
- [ ] obtain recording(s)

**Artifact archiving**
- [ ] upload recording(s) to YouTube
- [ ] upload artifacts to i-p.o Media Library
  - [ ] slides
  - [ ] Q&A
  - [ ] additional materials
- [ ] add archive information to webinar record
  - [ ] archives

**Webinar followup communications**
- [ ] *update ECP training site*
- [ ] update <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [ ] remove full **upcoming** event
  - [ ] add full **past** event
- [ ] update <https://ideas-productivity.org/events/>
  - [ ] remove **upcoming** event bullet
  - [ ] add **past** event bullet
- [ ] update <https://ideas-productivity.org/>
  - [ ] remove **upcoming** event bullet
- [ ] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/hpcbp-webinars-cc.md>
- [ ] update MailChimp audience w/ appropriate tag
  - [ ] add webinar registrants w/ appropriate tag
  - [ ] add webinar participants w/ appropriate tag
- [ ] prepare and send MailChimp campaign to appropriate tag

Note: items in *italics* are usually performed by Osni.  Items in regular font are usually performed by David.
