### ISSUE TITLE
036-exxalt checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/hpc-best-practices-webinars#25]
**Preparing to advertise webinar**
- [x] collect initial webinar information
  - [ ] webinar `date`
  - [ ] webinar `title`
  - [ ] webinar abstract
  - [ ] presenter name(s)
  - [ ] presenter email(s)
  - [ ] presenter affiliation(s)
  - [ ] presenter github id(s)
  - [ ] presenter bio(s)
- [x] technical editor checks webinar abstract
- [x] create presenter record(s)
- [x] create webinar record
- [x] verify content and formatting
- [x] *update EventBrite*
  - [ ] *add full upcoming event*
  - [ ] obtain `registration-url`
  - [ ] add `registration-url` to webinar record
- [x] verify content and formatting

**Advertising webinar**
- [x] *update ECP training site*
  - [ ] *add full upcoming event*
  - [ ] obtain `ecp-abbreviation`
  - [ ] add `ecp-abbreviation` to webinar record
- [x] verify content and formatting
- [x] update i-p.o site
  - [ ] add full upcoming event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [ ] add upcoming event bullet to <https://ideas-productivity.org/events/>
  - [ ] add upcoming event bullet to <https://ideas-productivity.org/>
- [x] add BSSw Event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
- [x] prepare and send MailChimp campaign to full audience

**Preparing for event**
- [x] add event metadata
  - [ ] vtc-url
  - [ ] vtc-session
  - [ ] vtc-password
  - [ ] qa-public-url
  - [ ] survey public-url
- [x] *send connection email*

**Post-event artifact collection**
- [x] obtain webinar registration list
- [x] obtain webinar participation list
- [x] obtain slides
- [x] obtain Q&A
- [x] obtain recording(s)

**Artifact archiving**
- [x] upload recording(s) to YouTube
- [x] upload artifacts to i-p.o Media Library
  - [x] slides
  - [x] Q&A
  - [ ] additional materials
- [x] add archive information to webinar record
  - [x] archives

**Webinar followup communications**
- [ ] *update ECP training site*
- [x] update <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [x] remove full **upcoming** event
  - [x] add full **past** event
- [x] update <https://ideas-productivity.org/events/>
  - [x] remove **upcoming** event bullet
  - [x] add **past** event bullet
- [x] update <https://ideas-productivity.org/>
  - [x] remove **upcoming** event bullet
- [x] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/hpcbp-webinars-cc.md>
- [x] update MailChimp audience w/ appropriate tag
  - [x] add webinar registrants w/ appropriate tag
  - [x] add webinar participants w/ appropriate tag
- [x] prepare and send MailChimp campaign to appropriate tag

Note: items in *italics* are usually performed by Osni.  Items in regular font are usually performed by David.
