### ISSUE TITLE
038-testing checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/hpc-best-practices-webinars#28]
**Preparing to advertise webinar**
- Collect initial webinar information
  - [x] webinar `date`
  - [x] webinar `title`
  - [x] webinar abstract
  - [x] presenter name(s)
  - [x] presenter email(s)
  - [x] presenter affiliation(s)
  - [x] presenter github id(s)
  - [x] presenter bio(s)
- [x] technical editor checks webinar abstract
- Add presenter(s) and webinar to GitHub repo
  - [x] create presenter record(s)
  - [x] create webinar record
  - [x] verify content and formatting
- *Update EventBrite*
  - [ ] *add full upcoming event*
  - [x] obtain `registration-url`
- [x] Add `registration-url` to webinar record in GitHub repo

**Advertising webinar**
- *Update ECP training site*
  - [ ] *add full upcoming event*
  - [x] obtain `ecp-abbreviation`
- [x] Add `ecp-abbreviation` to webinar record in GitHub repo
- Update i-p.o site
  - [x] add full upcoming event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [x] add upcoming event bullet to <https://ideas-productivity.org/events/>
  - [x] add upcoming event bullet to <https://ideas-productivity.org/>
- Add BSSw Event 
  - [x] add event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
  - [ ] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/Site/Announcements/Announcements.md>
- Prepare and send MailChimp campaign to full audience
  - [x] add audience from most recent webinar
  - [x] prepare campaign
  - [x] schedule distribution of email

**Preparing for event**
- Add event metadata
  - [x] `vtc-url`
  - [x] `vtc-session`
  - [x] `vtc-password`
  - [x] `qa-public-url`
  - [x] `survey public-url`
- [ ] *send connection email*

**Post-event artifact collection**
- [x] obtain webinar registration list
- [x] obtain webinar participation list
- [x] obtain slides
- [x] obtain Q&A
- [x] obtain recording(s)

**Post-event announcement updates**
- Update i-p.o site
  - [x] remove **upcoming** event from <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [x] add **to be archived** past event to <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
  - [x] remove **upcoming** event bullet to <https://ideas-productivity.org/events/>
  - [x] add **past** event bullet to <https://ideas-productivity.org/events/>
  - [x] remove **upcoming** event bullet from <https://ideas-productivity.org/>

**Artifact archiving**
- [x] upload recording(s) to YouTube
- Upload artifacts to i-p.o Media Library
  - [x] slides
  - [x] Q&A
  - [ ] additional materials
- Add archive information to webinar record
  - [x] `archives`

**Webinar followup communications**
- [ ] *update ECP training site*
- Update i-p.o site
  - [x] update past event with archives on <https://ideas-productivity.org/events/hpc-best-practices-webinars/>
- [x] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/hpcbp-webinars-cc.md>
- Update MailChimp audience w/ appropriate tag
  - [x] add webinar registrants w/ appropriate tag
  - [x] add webinar participants w/ appropriate tag
- [x] prepare and send MailChimp campaign to appropriate tag

Note: items in *italics* are usually performed by Osni.  Items in regular font are usually performed by David.
